<?php
/**
 * @file
 * A module that allows pushing message through pushbullet.com service.
 */

/**
 * Implements hook_menu().
 */
function pushbullet_menu() {
  $items = array();
  $items['admin/config/services/pushbullet'] = array(
    'title' => 'Pushbullet',
    'description' => 'Pushing messages',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('pushbullet_push_form'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'includes/push_form.admin.inc',
  );
  $items['admin/config/services/pushbullet/push'] = array(
    'title' => 'Push message',
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  $items['admin/config/services/pushbullet/settings'] = array(
    'title' => 'Pushbullet settings',
    'description' => 'Configuration for the pushbullet module',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('pushbullet_config_form'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'includes/config_form.admin.inc',
  );
  return $items;
}

/**
 * Pushes messages
 */
function pushbullet_push($type, $parameters) {
  /* Include the pushbullet class. */
  module_load_include('inc', 'pushbullet', 'includes/pushbullet.class');

  try {
    $p = new PushbulletPushBullet(variable_get('pushbullet_api_key'));
    switch ($type) {
      case "note":
        $p->pushNote('my', $parameters['title'], $parameters['message']);
        break;
    }
    drupal_set_message(t('A message was pushed to your devices'), 'status');
  }
  catch (PushbulletPushBulletException $e) {
    drupal_set_message(t('An error occurred while pushing your messages: "@message"', array('@message' => $e->getMessage())), 'error');
  }
}
