<?php
/**
 * @file
 * A module that allows pushing message through pushbullet.com service.
 */

/* Include the pushbullet class. */
module_load_include('inc', 'pushbullet', 'includes/pushbullet.class');

/**
 * Implements hook_menu().
 */
function pushbullet_menu() {
  $items = array();
  $items['admin/config/services/pushbullet'] = array(
    'title' => 'Pushbullet',
    'description' => 'Pushing messages',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('pushbullet_push_form'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'includes/push_form.admin.inc',
  );
  $items['admin/config/services/pushbullet/push'] = array(
    'title' => 'Push',
    'description' => 'Pushing messages',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('pushbullet_push_form'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'file' => 'includes/push_form.admin.inc',
  );
  $items['admin/config/services/pushbullet/settings'] = array(
    'title' => 'Pushbullet settings',
    'description' => 'Configuration for the pushbullet module',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('pushbullet_config_form'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'includes/config_form.admin.inc',
  );
  return $items;
}
